version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
    networks:
      - webapp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: my_mysql_username
      MYSQL_PASSWORD: my_mysql_password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - webapp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: my-zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOO_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - webapp

  kafka:
    image: bitnami/kafka:3.8.0
    container_name: my-kafka
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "my-zookeeper:2181"
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_TOPIC: "EMAIL_SENDING_TASKS"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - webapp

  frontend:
    build:
      context: ../task-schedule/task-schedule-front
      dockerfile: dockerfile
    container_name: task-schedule-front
    ports:
      - "8081:8081"
    networks:
      - webapp

  email-sender:
    build:
      context: ../task-schedule/task-schedule-email-sender
      dockerfile: dockerFile
    container_name: task-schedule-email-sender
    ports:
      - "8082:8082"
    networks:
      - webapp

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  webapp:
    driver: bridge
