version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    volumes:
      - ~/data/redis:/var/lib/redis
      - ~/data/redis/config:/usr/local/etc/redis/redis.conf
    networks:
      webapp:
        aliases:
          - my-redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: my_mysql_username
      MYSQL_PASSWORD: my_mysql_password
      MYSQL_DATABASE: database
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      webapp:
        aliases:
          - my-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: my-zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOO_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      webapp:
        aliases:
          - my-zookeeper

  kafka:
    image: bitnami/kafka:3.8.0
    container_name: my-kafka
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_TOPIC: EMAIL_SENDING_TASKS
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      webapp:
        aliases:
          - my-kafka

  backend:
    image: dragomirovcode/task-schedule-backend
    container_name: app
    depends_on:
      - db
      - kafka
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql:3306/database
      SPRING_DATASOURCE_USERNAME: my_mysql_username
      SPRING_DATASOURCE_PASSWORD: my_mysql_password
      SPRING_DATA_REDIS_URL: redis://my-redis:6379
      SPRING_DATA_REDIS_HOST: my-redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - webapp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: dragomirovcode/task-schedule-front
    container_name: task-schedule-front
    depends_on:
      - backend
    ports:
      - "8081:8081"
    networks:
      - webapp
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  email-sender:
    image: dragomirovcode/task-schedule-email-sender
    container_name: task-schedule-email-sender
    depends_on:
      - backend
    ports:
      - "8082:8082"
    networks:
      - webapp
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  task-scheduler:
    image: dragomirovcode/task-scheduler:latest
    container_name: task-scheduler
    depends_on:
      - backend
      - email-sender
    ports:
      - "8083:8083"
    networks:
      - webapp
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  webapp:
    driver: bridge
    name: webapp